#!/usr/bin/env perl

use strict;
use warnings;
use lib 'lib';

use Getopt::Long qw(GetOptions);
use Pod::Usage qw(pod2usage);
use Term::ProgressBar qw(progress_bar);
use Parallel::ForkManager;
use File::Spec;
use File::Path qw(make_path);
use Anime::Saturn::Scraper;
use Anime::Saturn::Anime;

my $help    = 0;
my $version = 0;
my $action  = '';
my $query   = '';
my $output  = './downloads';
my $jobs    = 4;

GetOptions(
    'help|h'     => \$help,
    'version|v'  => \$version,
    'output|o=s' => \$output,
    'jobs|j=i'   => \$jobs,
) or pod2usage(2);

pod2usage(1) if $help;

if ($version) {
    print "anime-dl version 1.0.0 (Perl 5 port)\n";
    exit 0;
}

# Get action and query from remaining arguments
if (@ARGV < 2) {
    pod2usage("Error: Missing action and/or query argument\n");
}

$action = shift @ARGV;
$query  = shift @ARGV;

my $scraper = Anime::Saturn::Scraper->new();

if ($action eq 'search') {
    do_search($scraper, $query);
}
elsif ($action eq 'fetch') {
    do_fetch($scraper, $query);
}
elsif ($action eq 'download') {
    do_download($scraper, $query, $output, $jobs);
}
elsif ($action eq 'stream') {
    do_stream($scraper, $query);
}
elsif ($action eq 'plot') {
    do_plot($scraper, $query);
}
else {
    pod2usage("Error: Unknown action '$action'\n");
}

sub do_search {
    my ($scraper, $query) = @_;
    
    print "Searching for: $query\n";
    my $results = $scraper->search_anime($query);
    
    if (@$results == 0) {
        print "No results found.\n";
        return;
    }
    
    print "Found " . scalar(@$results) . " results:\n";
    for my $i (0 .. $#{$results}) {
        printf "%d. %s\n", $i + 1, $results->[$i];
    }
}

sub do_fetch {
    my ($scraper, $anime_name) = @_;
    
    print "Fetching episodes for: $anime_name\n";
    my $episodes = $scraper->fetch_anime($anime_name);
    
    if (@$episodes == 0) {
        print "No episodes found.\n";
        return;
    }
    
    print "Found " . scalar(@$episodes) . " episodes:\n";
    for my $i (0 .. $#{$episodes}) {
        printf "%d. %s\n", $i + 1, $episodes->[$i];
    }
}

sub do_download {
    my ($scraper, $anime_name, $output_dir, $max_jobs) = @_;
    
    print "Downloading episodes for: $anime_name\n";
    print "Output directory: $output_dir\n";
    print "Using $max_jobs parallel jobs\n";
    
    # Create output directory
    make_path($output_dir) unless -d $output_dir;
    
    # Fetch episode list
    my $episode_urls = $scraper->fetch_anime($anime_name);
    
    if (@$episode_urls == 0) {
        print "No episodes found to download.\n";
        return;
    }
    
    print "Found " . scalar(@$episode_urls) . " episodes to download.\n";
    
    my $pm = Parallel::ForkManager->new($max_jobs);
    my $progress = Term::ProgressBar->new(scalar(@$episode_urls));
    $progress->name("Downloading");
    my $count = 0;
    
    $pm->run_on_finish(sub {
        $count++;
        $progress->update($count);
    });
    
    for my $i (0 .. $#{$episode_urls}) {
        my $ep_url = $episode_urls->[$i];
        my $ep_num = $i + 1;
        
        $pm->start and next;
        
        eval {
            my $anime_obj = $scraper->fetch_episodes($ep_url, $anime_name);
            
            unless ($anime_obj) {
                warn "Failed to fetch episode $ep_num: $ep_url\n";
                $pm->finish;
                return;
            }
            
            my $filename = sprintf("%s/episode_%03d.mp4", $output_dir, $ep_num);
            
            # Download the video file
            my $http = HTTP::Tiny->new;
            my $response = $http->get($anime_obj->url, {
                headers => {
                    Referer => $anime_obj->an,
                },
                data_callback => sub {
                    open(my $fh, '>>', $filename) or die "Cannot open $filename: $!\n";
                    binmode($fh);
                    print $fh $_[0];
                    close($fh);
                },
            });
            
            if ($response->{success}) {
                print "\nDownloaded: $filename\n";
            } else {
                warn "Failed to download episode $ep_num: $response->{status}\n";
            }
        };
        if ($@) {
            warn "Error downloading episode $ep_num: $@\n";
        }
        
        $pm->finish;
    }
    
    $pm->wait_all_children;
    print "\nDownload complete!\n";
}

sub do_stream {
    my ($scraper, $episode_url) = @_;
    
    print "Preparing stream for: $episode_url\n";
    
    # For streaming, we extract the direct media URL
    # In a real implementation, this would pipe to a media player
    my $anime_name = $episode_url;
    $anime_name =~ s|.*/anime/||;
    $anime_name =~ s|/.*||;
    
    my $anime_obj = $scraper->fetch_episodes($episode_url, $anime_name);
    
    unless ($anime_obj) {
        print "Failed to fetch stream URL.\n";
        return;
    }
    
    print "Stream URL: " . $anime_obj->url . "\n";
    print "Referer: " . $anime_obj->an . "\n";
    print "\nTo stream with VLC:\n";
    print "vlc --http-referrer=\"" . $anime_obj->an . "\" \"" . $anime_obj->url . "\"\n";
}

sub do_plot {
    my ($scraper, $anime_name) = @_;
    
    print "Fetching plot for: $anime_name\n";
    my $plot = $scraper->plot_anime($anime_name);
    
    if ($plot) {
        print "\nPlot Summary:\n";
        print "-" x 60 . "\n";
        print "$plot\n";
        print "-" x 60 . "\n";
    } else {
        print "No plot summary found.\n";
    }
}

__END__

=head1 NAME

anime-dl - Anime Saturn downloader and streamer

=head1 SYNOPSIS

  anime-dl [options] <action> <query>

  Actions:
    search   <query>           Search for anime by name
    fetch    <anime_name>      Fetch episode list for an anime
    download <anime_name>      Download all episodes of an anime
    stream   <episode_url>     Get streaming URL for an episode
    plot     <anime_name>      Show plot summary for an anime

=head1 OPTIONS

  -h, --help         Show this help message
  -v, --version      Show version information
  -o, --output DIR   Output directory for downloads (default: ./downloads)
  -j, --jobs NUM     Number of parallel download jobs (default: 4)

=head1 EXAMPLES

  # Search for an anime
  anime-dl search "naruto"

  # Fetch episode list
  anime-dl fetch naruto

  # Download all episodes
  anime-dl download naruto

  # Download with custom output directory and parallel jobs
  anime-dl -o ./anime -j 8 download naruto

  # Get streaming URL
  anime-dl stream "https://www.animesaturn.tv/..."

  # Show plot summary
  anime-dl plot naruto

=head1 DESCRIPTION

anime-dl is a command-line tool for searching, downloading, and streaming
anime from AnimeSaturn. It supports parallel downloads and provides
multiple actions for interacting with the anime database.

=head1 AUTHOR

Ported to Perl 5 following best practices.

=head1 LICENSE

This software is provided as-is for educational purposes.

=cut
